### PR TITLE
New ru-translation

### PR DESCRIPTION
**Pull request by sinya13**
New changes from en-US added.

### CODE REVIEW

**Comment by jobisoft** [comment]
Thanks! You created a new Pull Request? I think that was not needed (I hope it was no extra work). I updated the old Pull Request (I updated YOUR files) and you could have just make the changes within the old Pull Request.

Thanks for your support!

**Comment by jobisoft** [comment]
Lets try that next time, just for fun :-) 

You forked my project and worked on your own local copy. You edited YOUR files. When you where done, you created a PR (Pull request) which sends all the changes you made to me. If you realize that you forgot something after you created the PR, you can just continue to edit your files and these new changes will be automatically part of your already open PR.

After you created a PR, I have write access to YOUR files and I actually changed your files to reflect the current state (you can see that [here](https://github.com/jobisoft/DAV-4-TbSync/pull/46/commits) at the bottom).

After I changed your files, you could have just continue to edit/update your files and the missing translations would have landed in the PR.

Thanks for your contributions,
John

**Comment by sinya13** [comment]
Ок, understand. Don't mention it! Glad to help make a good app! I myself do not know how to do javascript.

**Comment by jobisoft** [comment]
@sinya13 I just updated the DAV provider, because the new setup wizzard needs more locales than I assumed. Sorry. This is how it will look like. Do you know any other providers I could add?

image

image

**Comment by sinya13** [comment]
I added a new translation.

**Pull request merged**
