### PR TITLE
Updated Max Version to 88.* - Testing seems fine

### PR DESCRIPTION
**Pull request by denisabt**
Version update to work with current TB Version. Testing seems fine for my config

### CODE REVIEW

**Comment by LeKangouroo** [comment]
@jobisoft is this version bump ok for you ?

**Comment by jobisoft** [comment]
Not really, there are a few things which are broken in 88 and I am currently preparing a new version.

**Comment by LeKangouroo** [comment]
OK cool. Please tell us if you need help for anything.

Cheers

**Comment by jobisoft** [comment]
I have test versions for TbSync + DAV for Thunderbird 91. Could you try them in a new profile?
[TbSync-beta.zip](https://github.com/jobisoft/TbSync/files/6888914/TbSync-beta.zip)
[DAV-4-TbSync.zip](https://github.com/jobisoft/TbSync/files/6888917/DAV-4-TbSync.zip)

You can just install the ZIP files (via the gear icon in the add-on manager -> Install Add-on From File...) , no need to rename them to XPI.

Thanks.  I will close this PR, but you can still comment and report, if the test versions are working for you.

**Pull request closed without merging**
