### PR TITLE
fix calendar sync for TB102

### PR DESCRIPTION
**Pull request by kxxt**
Although I'm not using DAV-4-TbSync personally, many people depend on this addon for data sync.

Fixing calendar sync for this addon is very easy as I have done the same to TbSync and EAS-4-TbSync.

I test it with a fruux account and it works, but I haven't update the old synchronous calls to calendar methods.

### CODE REVIEW

**Comment by kxxt** [comment]
@jobisoft Is this addon still necessary? Or should this add-on be deprecated because thunderbird now supports built-in support for CalDAV?

**Comment by jobisoft** [comment]
The public demand is to keep it alive, as it makes subscribing to address books and calendars easier. Once EAS is done, I will take care of this. I will rip out contact sync and replace it with setting up carddav addressbooks (type 102 instead of 101), so syncing will be fully done by TB.

This PR is a good start, thanks!

**Comment by kxxt** [comment]
Any ideas on this function call? 

https://github.com/jobisoft/DAV-4-TbSync/blob/c8324126a8a7852f3a6b53d9ac07cc1aca7d7346/content/includes/GoogleDavCalendar.jsm#L1132-L1136

I'm not pretty sure what `mOfflineStorage` is.

Is this a calendar object? Does `getItem` return `Promise` in TB 102?

**Comment by jobisoft** [comment]
> GoogleDavCalendar.jsm

That file does not seem to be used at all (I think I kept it because it showed how to create a custom calendar type)

**Comment by jobisoft** [comment]
Could you change the PR to be merged in TB102 branch? I do not seem able to do that.

**Comment by kxxt** [comment]
done

**Pull request merged**
