### PR TITLE
Update localization for Bulgarian

### PR DESCRIPTION
**Pull request by dilyanpalauzov**
* Update localization for Bulgarian
* Fix quotes and end-of-line spaces in _locales/de and en-US.

### CODE REVIEW

**Comment by jobisoft** [comment]
Hold on! I am just now moving to https://crowdin.com to simplify translations. I have to reject this, as I am currently restructuring.

**Comment by jobisoft** [comment]
I movd translation to crowdin:
https://crowdin.com/project/dav-4-tbsync

If you click on the Bulgarien language and than select "proof reading mode", you see a few suggestions.

Wanna give it a try? It is all new to me as well, but I think the online editor in general is much easier to use than text files.

image

**Comment by dilyanpalauzov** [comment]
I do not see a “Open in proofreading mode” in that menu.

**Comment by jobisoft** [comment]
What do you see? Can you update any locales? Can you request access rights somehow (if you want that)?

**Comment by dilyanpalauzov** [comment]
I click on the ellipsis on the right after master, _locales or anything else and I see only “Translate” and “Open in voting mode”. As a matter of fact, the only locale that is shown in the file-browser approximation is en-US and only on it I have ellipsis menu.

**Comment by jobisoft** [comment]
But you did manage to update the Bulgarien translation, at least I got a change? Someone added "TbSync" somewhere?

**Comment by dilyanpalauzov** [comment]
Yes, but this is not a contradiction to what I said.

**Comment by dilyanpalauzov** [comment]
Yes, I managed to update the translation, but cannot do proofreading.

**Comment by jobisoft** [comment]
I just learned how to do it. I had to switch of public access rights. If you now want to change something, you have to become a member of the team (which I would appreciate) and then I can give you proofread access rights. You would also get an email, if new strings have been added.

Wanna give it  a try?

**Pull request merged**
