### PR TITLE
Improved SOGo shared addressbook ACL handling

### LINKED ISSUE #158: Readonly shared address books are not discovered with SOGo
This is an extension to #114, but for the case where the addressbook is shared with readonly access. In this case the `current-user-privilege-set` is completely empty. This has already been added to to Bugreport at SOGo,

As there is some kind of indirect SOGo detection for lenient handling of PROPFIND on the calendar-proxy-read/write, this could trigger a lenient handling of ACLs, too. 

I'll submit a PR for this.

### PR DESCRIPTION
**Pull request by erwint**
Fixes #158

### CODE REVIEW

**Comment by jobisoft** [comment]
I really do not like that. What is the ETA of the bugfix in sogo? Isn‘t the sogo connector the better choice for you?

**Comment by erwint** [comment]
From the lack of reaction and from other ticket I'd say the ETA is far, far in the future. Also, the SOGo connector does not have a TB68 release yet and has not such a nice setup

**Comment by erwint** [comment]
BTW: if you have any better ideas I'd be glad to adapt the PR

**Comment by jobisoft** [comment]
I do not want to bind sogoQuirks to the 403, as SOGo uses two different methods to share resources (depends on the version of SOGo the account was created and/or resources where shared) and this is all on ebig mess.

Is there any other way to detect SOGo? Is SOGo always using /SOGo/dav as URL?

**Comment by erwint** [comment]
I looked at all the responses and headers and found no indicator by which you could identify SOGo, but indeed the /SOGo/dav part seems hardcoded into SOGo, so we could use that INSTEAD of the 403 detection, if that is what you suggest (then I would change the PR later today)?

**Comment by jobisoft** [comment]
yes, that would be nice. 

Please rename `sogoQuirks` to `isSogo`. Inside the for-job-in-davjobs-loop you can use `davjobs[job].server` to test for sogo, I think.

**Comment by jobisoft** [comment]
I moved some things around and I want to keep "allow read if write given" as other servers might have that issue as well.

**Comment by jobisoft** [comment]
It is released on my beta release channel!

**Pull request merged**
