### PR TITLE
Add pt-BR (Portuguese Brazilian) translation 

### PR DESCRIPTION
**Pull request by wanderleihuttel**

### CODE REVIEW

**Comment by jobisoft** [comment]
Could you also provide Translation for tbsync itself?
https://github.com/jobisoft/TbSync

**Comment by jobisoft** [comment]
I just released a new beta including your translations and the new dav group feature. If you want to test your translations, go beta:
https://tbsync.jobisoft.de

I suggest to disable your account in TbSync before installing the beta, and re-enable it after you have installed the beta.

The dav groups are used by iCloud:
image

And are mapped to TB Mailing lists:
image

Other servers also honor groups, for example nextcloud. They just do not show them correctly in the webinterface, but with the group feature it is now possible to sync TB mailinglists to the server.

Happy testing.

**Comment by wanderleihuttel** [comment]
Hello @jobisoft !
I've followed your steps and couldn't see the translations.
Maybe is because is necessary to include in the install.rdf?

**Comment by jobisoft** [comment]
Oh, I thought you did that. Yes you need to add your translation to both index.rdf

**Comment by jobisoft** [comment]
Just create a new PR.

**Pull request merged**
